stages:
- buildimage
- createcontainer
- pushimage

buildimage:
  tags:
  - vadapav
  stage: buildimage
  script:
    - docker rmi -f trainer/orange:webserver || true
    - docker build . -f Dockerfile -t trainer/orange:webserver --no-cache
    

createcontainerjob:
  needs:
    - buildimage
  
  tags:
  - vadapav
  stage: createcontainer
  script:
    - docker rm -f webserver-trainer || true
    - docker run -d --name webserver-trainer -p 9090:80 trainer/orange:webserver

pushimage:
  needs:
    - buildimage
  tags:
  - vadapav
  stage: pushimage
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker tag trainer/orange:webserver $CI_REGISTRY_IMAGE/webserver:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/webserver:$CI_COMMIT_SHA