stages:
  - orangestage
  - build

trigger_a_pipeline:
  stage: orangestage
  trigger:
    include: a/.gitlab-ci.yml
  # rules:
  #   - changes:
  #       - a/*
trigger_b_pipeline:
  stage: orangestage
  trigger:
    include: b/.gitlab-ci.yml
  # rules:
  #   - changes:
  #       - b/*
test_job:
  stage: build
  script:
    - echo "This job runs in the main pipeline."